id: PYSEC-0000-CVE-2013-4260
package:
  name: ansible
  ecosystem: PyPI
details: lib/ansible/playbook/__init__.py in Ansible 1.2.x before 1.2.3, when playbook
  does not run due to an error, allows local users to overwrite arbitrary files via
  a symlink attack on a retry file with a predictable name in /var/tmp/ansible/.
affects:
  ranges:
  - type: ECOSYSTEM
    introduced: 1.2.0
    fixed: 1.2.3
references:
- type: WEB
  url: https://bugzilla.redhat.com/show_bug.cgi?id=998227
- type: WEB
  url: http://www.ansible.com/security
- type: WEB
  url: https://exchange.xforce.ibmcloud.com/vulnerabilities/86898
- type: WEB
  url: https://groups.google.com/forum/#!topic/ansible-project/UVDYW0HGcNg
aliases:
- CVE-2013-4260
modified: "2018-10-30T16:28:00Z"
published: "2013-09-16T19:14:00Z"
