id: PYSEC-2020-205
package:
  name: ansible
  ecosystem: PyPI
details: Multiple argument injection vulnerabilities in Ansible before 1.6.7 allow
  remote attackers to execute arbitrary code by leveraging access to an Ansible managed
  host and providing a crafted fact, as demonstrated by a fact with (1) a trailing
  " src=" clause, (2) a trailing " temp=" clause, or (3) a trailing " validate=" clause
  accompanied by a shell command.
affects:
  ranges:
  - type: GIT
    repo: https://github.com/ansible/ansible
    fixed: 62a1295a3e08cb6c3e9f1b2a1e6e5dcaeab32527
  - type: ECOSYSTEM
    fixed: 1.6.7
  versions:
  - "1.0"
  - "1.1"
  - "1.2"
  - 1.2.1
  - 1.2.2
  - 1.2.3
  - 1.3.0
  - 1.3.1
  - 1.3.2
  - 1.3.3
  - 1.3.4
  - "1.4"
  - 1.4.1
  - 1.4.2
  - 1.4.3
  - 1.4.4
  - 1.4.5
  - "1.5"
  - 1.5.1
  - 1.5.2
  - 1.5.3
  - 1.5.4
  - 1.5.5
  - "1.6"
  - 1.6.1
  - 1.6.2
  - 1.6.3
  - 1.6.4
  - 1.6.5
  - 1.6.6
references:
- type: WEB
  url: https://github.com/ansible/ansible/commit/62a1295a3e08cb6c3e9f1b2a1e6e5dcaeab32527
- type: WEB
  url: http://www.ocert.org/advisories/ocert-2014-004.html
aliases:
- CVE-2014-4967
modified: "2021-07-02T02:41:33.376176Z"
published: "2020-02-18T15:15:00Z"
