id: PYSEC-2018-37
package:
  name: ansible
  ecosystem: PyPI
details: A flaw was found in Ansible before version 2.2.0. The apt_key module does
  not properly verify key fingerprints, allowing remote adversary to create an OpenPGP
  key which matches the short key ID and inject this key instead of the correct key.
affects:
  ranges:
  - type: ECOSYSTEM
    fixed: 2.2.0.0
  versions:
  - "1.0"
  - "1.1"
  - "1.2"
  - 1.2.1
  - 1.2.2
  - 1.2.3
  - 1.3.0
  - 1.3.1
  - 1.3.2
  - 1.3.3
  - 1.3.4
  - "1.4"
  - 1.4.1
  - 1.4.2
  - 1.4.3
  - 1.4.4
  - 1.4.5
  - "1.5"
  - 1.5.1
  - 1.5.2
  - 1.5.3
  - 1.5.4
  - 1.5.5
  - "1.6"
  - 1.6.1
  - 1.6.10
  - 1.6.2
  - 1.6.3
  - 1.6.4
  - 1.6.5
  - 1.6.6
  - 1.6.7
  - 1.6.8
  - 1.6.9
  - "1.7"
  - 1.7.1
  - 1.7.2
  - "1.8"
  - 1.8.1
  - 1.8.2
  - 1.8.3
  - 1.8.4
  - 1.9.0
  - 1.9.0.1
  - 1.9.1
  - 1.9.2
  - 1.9.3
  - 1.9.4
  - 1.9.5
  - 1.9.6
  - 2.0.0
  - 2.0.0.0
  - 2.0.0.1
  - 2.0.0.2
  - 2.0.1.0
  - 2.0.2.0
  - 2.1.0.0
  - 2.1.1.0
  - 2.1.2.0
  - 2.1.3.0
  - 2.1.4.0
  - 2.1.5.0
  - 2.1.6.0
references:
- type: WEB
  url: https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2016-8614
- type: WEB
  url: https://github.com/ansible/ansible-modules-core/pull/5357
- type: WEB
  url: https://github.com/ansible/ansible-modules-core/pull/5353
- type: WEB
  url: https://github.com/ansible/ansible-modules-core/issues/5237
- type: WEB
  url: http://www.securityfocus.com/bid/94108
aliases:
- CVE-2016-8614
modified: "2021-07-02T02:41:33.569568Z"
published: "2018-07-31T21:29:00Z"
