id: PYSEC-2020-13
package:
  name: ansible
  ecosystem: PyPI
details: A flaw was found in the Ansible Engine affecting Ansible Engine versions
  2.7.x before 2.7.17 and 2.8.x before 2.8.11 and 2.9.x before 2.9.7 as well as Ansible
  Tower before and including versions 3.4.5 and 3.5.5 and 3.6.3 when the ldap_attr
  and ldap_entry community modules are used. The issue discloses the LDAP bind password
  to stdout or a log file if a playbook task is written using the bind_pw in the parameters
  field. The highest threat from this vulnerability is data confidentiality.
affects:
  ranges:
  - type: ECOSYSTEM
    introduced: 2.7.0
    fixed: 2.7.17
  - type: ECOSYSTEM
    introduced: 2.8.0
    fixed: 2.8.11
  - type: ECOSYSTEM
    introduced: 2.9.0
    fixed: 2.9.7
  versions:
  - 2.7.0
  - 2.7.1
  - 2.7.2
  - 2.7.3
  - 2.7.4
  - 2.7.5
  - 2.7.6
  - 2.7.7
  - 2.7.8
  - 2.7.9
  - 2.7.10
  - 2.7.11
  - 2.7.12
  - 2.7.13
  - 2.7.14
  - 2.7.15
  - 2.7.16
  - 2.8.0
  - 2.8.1
  - 2.8.2
  - 2.8.3
  - 2.8.4
  - 2.8.5
  - 2.8.6
  - 2.8.7
  - 2.8.8
  - 2.8.9
  - 2.8.10
  - 2.9.0
  - 2.9.1
  - 2.9.2
  - 2.9.3
  - 2.9.4
  - 2.9.5
  - 2.9.6
aliases:
- CVE-2020-1746
modified: '2020-05-26T17:38:00Z'
published: '2020-05-12T18:15:00Z'
references:
- type: WEB
  url: https://github.com/ansible/ansible/pull/67866
- type: WEB
  url: https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-1746
