id: PYSEC-0000-CVE-2016-8628
package:
  name: ansible
  ecosystem: PyPI
details: Ansible before version 2.2.0 fails to properly sanitize fact variables sent
  from the Ansible controller. An attacker with the ability to create special variables
  on the controller could execute arbitrary commands on Ansible clients as the user
  Ansible runs as.
affects:
  ranges:
  - type: ECOSYSTEM
    fixed: 2.2.0.0
  versions:
  - '1.0'
  - '1.1'
  - '1.2'
  - 1.2.1
  - 1.2.2
  - 1.2.3
  - 1.3.0
  - 1.3.1
  - 1.3.2
  - 1.3.3
  - 1.3.4
  - '1.4'
  - 1.4.1
  - 1.4.2
  - 1.4.3
  - 1.4.4
  - 1.4.5
  - '1.5'
  - 1.5.1
  - 1.5.2
  - 1.5.3
  - 1.5.4
  - 1.5.5
  - '1.6'
  - 1.6.1
  - 1.6.10
  - 1.6.2
  - 1.6.3
  - 1.6.4
  - 1.6.5
  - 1.6.6
  - 1.6.7
  - 1.6.8
  - 1.6.9
  - '1.7'
  - 1.7.1
  - 1.7.2
  - '1.8'
  - 1.8.1
  - 1.8.2
  - 1.8.3
  - 1.8.4
  - 1.9.0
  - 1.9.0.1
  - 1.9.1
  - 1.9.2
  - 1.9.3
  - 1.9.4
  - 1.9.5
  - 1.9.6
  - 2.0.0
  - 2.0.0.0
  - 2.0.0.1
  - 2.0.0.2
  - 2.0.1.0
  - 2.0.2.0
  - 2.1.0.0
  - 2.1.1.0
  - 2.1.2.0
  - 2.1.3.0
  - 2.1.4.0
  - 2.1.5.0
  - 2.1.6.0
aliases:
- CVE-2016-8628
modified: '2021-07-02T02:41:33.612895Z'
published: '2018-07-31T20:29:00Z'
references:
- type: WEB
  url: https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2016-8628
- type: WEB
  url: https://access.redhat.com/errata/RHSA-2016:2778
- type: WEB
  url: http://www.securityfocus.com/bid/94109
