id: PYSEC-2017-2
details: The user module in ansible before 1.6.6 allows remote authenticated users
  to execute arbitrary commands.
affected:
- package:
    name: ansible
    ecosystem: PyPI
    purl: pkg:pypi/ansible
  ranges:
  - type: GIT
    repo: https://github.com/ansible/ansible
    events:
    - introduced: "0"
    - fixed: 8ed6350e65c82292a631f08845dfaacffe7f07f5
  - type: ECOSYSTEM
    events:
    - introduced: "0"
    - fixed: 1.6.6
  versions:
  - "1.0"
  - "1.1"
  - "1.2"
  - 1.2.1
  - 1.2.2
  - 1.2.3
  - 1.3.0
  - 1.3.1
  - 1.3.2
  - 1.3.3
  - 1.3.4
  - "1.4"
  - 1.4.1
  - 1.4.2
  - 1.4.3
  - 1.4.4
  - 1.4.5
  - "1.5"
  - 1.5.1
  - 1.5.2
  - 1.5.3
  - 1.5.4
  - 1.5.5
  - "1.6"
  - 1.6.1
  - 1.6.2
  - 1.6.3
  - 1.6.4
  - 1.6.5
references:
- type: FIX
  url: https://github.com/ansible/ansible/commit/8ed6350e65c82292a631f08845dfaacffe7f07f5
- type: REPORT
  url: https://bugzilla.redhat.com/show_bug.cgi?id=1335551
aliases:
- CVE-2014-3498
modified: "2021-07-02T02:41:33.064199Z"
published: "2017-06-08T18:29:00Z"
