id: PYSEC-2020-161
package:
  name: ansible
  ecosystem: PyPI
summary: Vulnerability in ansible
details: A flaw was found in the solaris_zone module from the Ansible Community modules.
  When setting the name for the zone on the Solaris host, the zone name is checked
  by listing the process with the 'ps' bare command on the remote machine. An attacker
  could take advantage of this flaw by crafting the name of the zone and executing
  arbitrary commands in the remote host. Ansible Engine 2.7.15, 2.8.7, and 2.9.2 as
  well as previous versions are affected.
affects:
  ranges:
  - type: ECOSYSTEM
    fixed: 2.7.15
  - type: ECOSYSTEM
    introduced: 2.8.0
    fixed: 2.8.7
  - type: ECOSYSTEM
    introduced: 2.9.0
    fixed: 2.9.2
references:
- type: WEB
  url: https://github.com/ansible/ansible/pull/65686
- type: WEB
  url: https://bugzilla.redhat.com/show_bug.cgi?id=1776944
- type: WEB
  url: https://lists.debian.org/debian-lts-announce/2021/01/msg00023.html
aliases:
- CVE-2019-14904
modified: "2021-01-28T18:00:00Z"
published: "2020-08-26T03:15:00Z"
