id: PYSEC-2013-1
details: runner/connection_plugins/ssh.py in Ansible before 1.2.3, when using ControlPersist,
  allows local users to redirect a ssh session via a symlink attack on a socket file
  with a predictable name in /tmp/.
aliases:
- CVE-2013-4259
modified: '2021-07-02T02:41:32.926386Z'
published: '2013-09-16T19:14:00Z'
references:
- type: WEB
  url: https://bugzilla.redhat.com/show_bug.cgi?id=998223
- type: WEB
  url: http://www.ansible.com/security
- type: WEB
  url: https://groups.google.com/forum/#!topic/ansible-project/UVDYW0HGcNg
affected:
- package:
    name: ansible
    ecosystem: PyPI
  ranges:
  - type: ECOSYSTEM
    events:
    - introduced: '0'
    - fixed: 1.2.3
  versions:
  - '1.0'
  - '1.1'
  - '1.2'
  - 1.2.1
  - 1.2.2
