id: PYSEC-0000-CVE-2014-4658
package:
  name: ansible
  ecosystem: PyPI
details: The vault subsystem in Ansible before 1.5.5 does not set the umask before
  creation or modification of a vault file, which allows local users to obtain sensitive
  key information by reading a file.
affects:
  ranges:
  - type: ECOSYSTEM
    fixed: 1.5.5
  versions:
  - '1.0'
  - '1.1'
  - '1.2'
  - 1.2.1
  - 1.2.2
  - 1.2.3
  - 1.3.0
  - 1.3.1
  - 1.3.2
  - 1.3.3
  - 1.3.4
  - '1.4'
  - 1.4.1
  - 1.4.2
  - 1.4.3
  - 1.4.4
  - 1.4.5
  - '1.5'
  - 1.5.1
  - 1.5.2
  - 1.5.3
  - 1.5.4
aliases:
- CVE-2014-4658
modified: '2021-07-02T02:41:33.150700Z'
published: '2020-02-20T15:15:00Z'
references:
- type: WEB
  url: https://www.securityfocus.com/bid/68233
- type: WEB
  url: https://github.com/ansible/ansible/blob/release1.5.5/CHANGELOG.md
