id: PYSEC-2018-41
package:
  name: ansible
  ecosystem: PyPI
details: Ansible before versions 2.3.1.0 and 2.4.0.0 fails to properly mark lookup-plugin
  results as unsafe. If an attacker could control the results of lookup() calls, they
  could inject Unicode strings to be parsed by the jinja2 templating system, resulting
  in code execution. By default, the jinja2 templating language is now marked as 'unsafe'
  and is not evaluated.
affects:
  ranges:
  - type: GIT
    repo: https://github.com/ansible/ansible
    fixed: ed56f51f185a1ffd7ea57130d260098686fcc7c2
  - type: ECOSYSTEM
    fixed: 2.3.1.0
  - type: ECOSYSTEM
    introduced: 2.3.2.0
    fixed: 2.4.0.0
  versions:
  - "1.0"
  - "1.1"
  - "1.2"
  - 1.2.1
  - 1.2.2
  - 1.2.3
  - 1.3.0
  - 1.3.1
  - 1.3.2
  - 1.3.3
  - 1.3.4
  - "1.4"
  - 1.4.1
  - 1.4.2
  - 1.4.3
  - 1.4.4
  - 1.4.5
  - "1.5"
  - 1.5.1
  - 1.5.2
  - 1.5.3
  - 1.5.4
  - 1.5.5
  - "1.6"
  - 1.6.1
  - 1.6.10
  - 1.6.2
  - 1.6.3
  - 1.6.4
  - 1.6.5
  - 1.6.6
  - 1.6.7
  - 1.6.8
  - 1.6.9
  - "1.7"
  - 1.7.1
  - 1.7.2
  - "1.8"
  - 1.8.1
  - 1.8.2
  - 1.8.3
  - 1.8.4
  - 1.9.0
  - 1.9.0.1
  - 1.9.1
  - 1.9.2
  - 1.9.3
  - 1.9.4
  - 1.9.5
  - 1.9.6
  - 2.0.0
  - 2.0.0.0
  - 2.0.0.1
  - 2.0.0.2
  - 2.0.1.0
  - 2.0.2.0
  - 2.1.0.0
  - 2.1.1.0
  - 2.1.2.0
  - 2.1.3.0
  - 2.1.4.0
  - 2.1.5.0
  - 2.1.6.0
  - 2.2.0.0
  - 2.2.1.0
  - 2.2.2.0
  - 2.2.3.0
  - 2.3.0.0
  - 2.3.2.0
  - 2.3.3.0
references:
- type: WEB
  url: https://github.com/ansible/ansible/commit/ed56f51f185a1ffd7ea57130d260098686fcc7c2
- type: WEB
  url: https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2017-7481
- type: WEB
  url: https://access.redhat.com/errata/RHSA-2017:2524
- type: WEB
  url: https://access.redhat.com/errata/RHSA-2017:1599
- type: WEB
  url: https://access.redhat.com/errata/RHSA-2017:1499
- type: WEB
  url: https://access.redhat.com/errata/RHSA-2017:1476
- type: WEB
  url: https://access.redhat.com/errata/RHSA-2017:1334
- type: WEB
  url: https://access.redhat.com/errata/RHSA-2017:1244
- type: WEB
  url: http://www.securityfocus.com/bid/98492
- type: WEB
  url: https://usn.ubuntu.com/4072-1/
- type: WEB
  url: https://lists.debian.org/debian-lts-announce/2021/01/msg00023.html
aliases:
- CVE-2017-7481
modified: "2021-07-02T02:41:33.849138Z"
published: "2018-07-19T13:29:00Z"
