id: PYSEC-2020-201
package:
  name: ansible
  ecosystem: PyPI
details: Ansible before 1.5.5 sets 0644 permissions for sources.list, which might
  allow local users to obtain sensitive credential information in opportunistic circumstances
  by reading a file that uses the "deb http://user:pass@server:port/" format.
affects:
  ranges:
  - type: ECOSYSTEM
    fixed: 1.5.5
  versions:
  - "1.0"
  - "1.1"
  - "1.2"
  - 1.2.1
  - 1.2.2
  - 1.2.3
  - 1.3.0
  - 1.3.1
  - 1.3.2
  - 1.3.3
  - 1.3.4
  - "1.4"
  - 1.4.1
  - 1.4.2
  - 1.4.3
  - 1.4.4
  - 1.4.5
  - "1.5"
  - 1.5.1
  - 1.5.2
  - 1.5.3
  - 1.5.4
references:
- type: WEB
  url: https://www.securityfocus.com/bid/68234
- type: WEB
  url: https://github.com/ansible/ansible/blob/release1.5.5/CHANGELOG.md
aliases:
- CVE-2014-4659
modified: "2021-07-02T02:41:33.195519Z"
published: "2020-02-20T15:15:00Z"
