id: PYSEC-2020-2
package:
  name: ansible
  ecosystem: PyPI
summary: Vulnerability in ansible
details: An archive traversal flaw was found in all ansible-engine versions 2.9.x
  prior to 2.9.7, when running ansible-galaxy collection install. When extracting
  a collection .tar.gz file, the directory is created without sanitizing the filename.
  An attacker could take advantage to overwrite any file within the system.
affects:
  ranges:
  - type: ECOSYSTEM
    introduced: 2.9.0
    fixed: 2.9.7
references:
- type: WEB
  url: https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-10691
- type: WEB
  url: https://github.com/ansible/ansible/pull/68596
aliases:
- CVE-2020-10691
modified: "2020-05-21T14:49:00Z"
published: "2020-04-30T17:15:00Z"
