id: PYSEC-2019-74
package:
  name: ansible
  ecosystem: PyPI
summary: Vulnerability in ansible
details: In Ansible, all Ansible Engine versions up to ansible-engine 2.8.5, ansible-engine
  2.7.13, ansible-engine 2.6.19, were logging at the DEBUG level which lead to a disclosure
  of credentials if a plugin used a library that logged credentials at the DEBUG level.
  This flaw does not affect Ansible modules, as those are executed in a separate process.
affects:
  ranges:
  - type: ECOSYSTEM
    fixed: 2.6.20
  - type: ECOSYSTEM
    introduced: 2.7.0
    fixed: 2.7.14
  - type: ECOSYSTEM
    introduced: 2.8.0
    fixed: 2.8.6
references:
- type: WEB
  url: https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-14846
- type: WEB
  url: https://github.com/ansible/ansible/pull/63366
- type: WEB
  url: https://access.redhat.com/errata/RHSA-2019:3207
- type: WEB
  url: https://access.redhat.com/errata/RHSA-2019:3201
- type: WEB
  url: https://access.redhat.com/errata/RHSA-2019:3202
- type: WEB
  url: https://access.redhat.com/errata/RHSA-2019:3203
- type: WEB
  url: https://access.redhat.com/errata/RHSA-2020:0756
- type: WEB
  url: http://lists.opensuse.org/opensuse-security-announce/2020-04/msg00021.html
- type: WEB
  url: http://lists.opensuse.org/opensuse-security-announce/2020-04/msg00026.html
- type: WEB
  url: https://lists.debian.org/debian-lts-announce/2020/05/msg00005.html
- type: WEB
  url: https://lists.debian.org/debian-lts-announce/2021/01/msg00023.html
aliases:
- CVE-2019-14846
modified: "2021-03-26T22:15:00Z"
published: "2019-10-08T19:15:00Z"
