id: PYSEC-2019-146
details: ansible before versions 2.8.6, 2.7.14, 2.6.20 is vulnerable to a None
aliases:
- CVE-2019-14856
modified: '2021-07-02T02:41:34.512855Z'
published: '2019-11-26T14:15:00Z'
references:
- type: WEB
  url: https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-14856
- type: WEB
  url: https://access.redhat.com/errata/RHSA-2020:0756
- type: WEB
  url: http://lists.opensuse.org/opensuse-security-announce/2020-04/msg00021.html
- type: WEB
  url: http://lists.opensuse.org/opensuse-security-announce/2020-04/msg00026.html
affected:
- package:
    name: ansible
    ecosystem: PyPI
  ranges:
  - type: ECOSYSTEM
    events:
    - introduced: 2.6.0
    - fixed: 2.6.20
    - introduced: 2.7.0
    - fixed: 2.7.14
    - introduced: 2.8.0
    - fixed: 2.8.6
  versions:
  - 2.6.0
  - 2.6.1
  - 2.6.10
  - 2.6.11
  - 2.6.12
  - 2.6.13
  - 2.6.14
  - 2.6.15
  - 2.6.16
  - 2.6.17
  - 2.6.18
  - 2.6.19
  - 2.6.2
  - 2.6.3
  - 2.6.4
  - 2.6.5
  - 2.6.6
  - 2.6.7
  - 2.6.8
  - 2.6.9
  - 2.7.0
  - 2.7.1
  - 2.7.10
  - 2.7.11
  - 2.7.12
  - 2.7.13
  - 2.7.2
  - 2.7.3
  - 2.7.4
  - 2.7.5
  - 2.7.6
  - 2.7.7
  - 2.7.8
  - 2.7.9
  - 2.8.0
  - 2.8.1
  - 2.8.2
  - 2.8.3
  - 2.8.4
  - 2.8.5
