name: Actions to take on pushes to main
on: pull_request
jobs:
  analysis:
    continue-on-error: true
    name: Analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 64
    - uses: google/osv.dev/actions/analyze@fix-action
      with:
        analyze-git: false
        pr-base: HEAD~63
        skip-pattern: '.github/workflows/.*'
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
    - run: git commit -m 'Analysis'
    - run: git push
  assign:
    needs: analysis
    continue-on-error: true
    name: Assign IDs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.16.4'
    - run: |
        go install github.com/google/osv.dev/vulnfeeds/cmd/ids@latest
        ids -dir=./vulns -prefix PYSEC
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
      env:
        GONOPROXY: github.com/google/osv.dev
    - run: git commit -m 'Assign IDs'
    - run: git push
