name: Auto advisory import
on:
  schedule:
  - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  job:
    continue-on-error: false
    name: Auto import
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.16.4'
    - run: |
        wget http://pypa-advisory-db.storage.googleapis.com/triage/pypi_links.json
        wget http://pypa-advisory-db.storage.googleapis.com/triage/pypi_versions.json
    - run: |
        wget https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.json.zip
        unzip nvdcve-1.1-modified.json.zip
    - run: |
        go install github.com/google/osv/vulnfeeds/cmd/pypi@latest
        pypi -false_positives triage/false_positives.yaml \
            -nvd_json nvdcve-1.1-modified.json \
            -pypi_links pypi_links.json \
            -pypi_versions pypi_versions.json \
            -out_dir vulns \
            -without_notes
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add vulns
        git diff --cached
      env:
        GONOPROXY: github.com/google/osv
    - run: git diff --cached --quiet || git commit -m 'Auto import'
    - run: git push
